web:
  build: .
  ports:
    - "80:80"
  links:
    - db
  volumes_from:
    - app

db:
  image: mariadb
  restart: always
  volumes_from:
    - data
  environment:
    MYSQL_USER: user
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: project

adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db

app:
  image: php:7.0-apache
  volumes: 
        - .:/var/www/html
  command: "true"

data:
    image: mariadb
    volumes:
        - /var/lib/mysql
    command: "true"
